# These are supported funding model platforms

# GitHub Sponsors (Recommended)
github: nhatvu2003

# Ko-fi
ko_fi: nhatvu2003

# Buy Me A Coffee
custom: ["https://www.buymeacoffee.com/nhatvu2003", "https://paypal.me/nhatvu10092003"]